### ISSUE TITLE
Final Project Feedback

### ISSUE THREAD

**Issue by abakus00** [rashansmith/blockchain-developer-bootcamp-final-project#1]
Hi @rashansmith,

For certification, please can you add you Public Ethereum address to your Github?

**Comment by rashansmith** [comment]
@abakus00 I have added it to the deployed_address.txt file. Additionally, you can find it here: https://ropsten.etherscan.io/address/0xd7A4e18439eb3750FF3d9961965817b4bd31662F . If you are referencing a Public Ethereum Address for the certificate, I did not request to get it as a NFT as I thought this was optional.

**Comment by abakus00** [comment]
You are right. Your public Ethereum account to receive your certification as an NFT is optional. Just wanted to check back with you! It's fine that you opted out!

**Comment by rashansmith** [comment]
@abakus00 No problem, thank you!
